app/main/user/forms.py
# -*- coding:utf-8 -*-
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import Length, DataRequired, URL
from flask_pagedown.fields import PageDownField
from flask_wtf.file import FileField, FileAllowed
from app import avatars


class EditProfileForm(FlaskForm):
    name = StringField(u'username', validators=[DataRequired(message=u"I forgot to fill it out.!"), Length(1, 64, message=u"1 to 64 characters in length")])
    major = StringField(u'major', validators=[Length(0, 128, message=u"0 to 128 characters in length")])
    headline = StringField(u'Introduce yourself in one sentence', validators=[Length(0, 32, message=u"Length is less than 32 characters")])
    about_me = PageDownField(u"Personal profile")
    submit = SubmitField(u"save Changes")


class AvatarEditForm(FlaskForm):
    avatar_url = StringField('', validators=[Length(1, 100, message=u"The length is limited to 100 characters"), URL(message=u"Please fill in the correct URL")])
    submit = SubmitField(u"Save")


class AvatarUploadForm(FlaskForm):
    avatar = FileField('', validators=[FileAllowed(avatars, message=u"Only upload images allowed")])

app/main/user/__init__.py
from flask import Blueprint

user = Blueprint('user', __name__, url_prefix='/users', template_folder='templates')

from . import views

app/main/user/views.py
# -*- coding:utf-8 -*-
from flask import render_template, url_for, flash, redirect, request, abort, g
from flask_login import login_required, current_user
from app.models import User, Log, Permission
from .forms import EditProfileForm, AvatarEditForm, AvatarUploadForm
from app import db, avatars
from . import user
import json


@user.route('/')
@login_required
def index():
    page = request.args.get('page', 1, type=int)
    pagination = User.query.order_by(User.id.desc()).paginate(page, per_page=10)
    users = pagination.items
    return render_template("user.html", users=users, pagination=pagination, title=u"Registered user")


@user.route('/<int:user_id>/')
def detail(user_id):
    the_user = User.query.get_or_404(user_id)

    show = request.args.get('show', 0, type=int)
    if show != 0:
        show = 1

    page = request.args.get('page', 1, type=int)
    pagination = the_user.logs.filter_by(returned=show) \
        .order_by(Log.borrow_timestamp.desc()).paginate(page, per_page=5)
    logs = pagination.items

    return render_template("user_detail.html", user=the_user, logs=logs, pagination=pagination,
                           title=u"user: " + the_user.name)


@user.route('/<int:user_id>/edit/', methods=['GET', 'POST'])
@login_required
def edit(user_id):
    if current_user.id == user_id or current_user.can(Permission.UPDATE_OTHERS_INFORMATION):
        the_user = User.query.get_or_404(user_id)
        form = EditProfileForm()
        if form.validate_on_submit():
            the_user.name = form.name.data
            the_user.major = form.major.data
            the_user.headline = form.headline.data
            the_user.about_me = form.about_me.data
            db.session.add(the_user)
            db.session.commit()
            flash(u'The data has been updated successfully!', "info")
            return redirect(url_for('user.detail', user_id=user_id))
        form.name.data = the_user.name
        form.major.data = the_user.major
        form.headline.data = the_user.headline
        form.about_me.data = the_user.about_me

        return render_template('user_edit.html', form=form, user=the_user, title=u"Edit information")
    else:
        abort(403)


@user.route('/<int:user_id>/avatar_edit/', methods=['GET', 'POST'])
@login_required
def avatar(user_id):
    if current_user.id == user_id or current_user.can(Permission.UPDATE_OTHERS_INFORMATION):
        the_user = User.query.get_or_404(user_id)
        avatar_edit_form = AvatarEditForm()
        avatar_upload_form = AvatarUploadForm()
        if avatar_upload_form.validate_on_submit():
            if 'avatar' in request.files:
                forder = str(user_id)
                avatar_name = avatars.save(avatar_upload_form.avatar.data, folder=forder)
                the_user.avatar = json.dumps({"use_out_url": False, "url": avatar_name})
                db.session.add(the_user)
                db.session.commit()
                flash(u'The avatar update is successful!', 'success')
                return redirect(url_for('user.detail', user_id=user_id))
        if avatar_edit_form.validate_on_submit():
            the_user.avatar = json.dumps({"use_out_url": True, "url": avatar_edit_form.avatar_url.data})
            db.session.add(the_user)
            db.session.commit()
            return redirect(url_for('user.detail', user_id=user_id))
        return render_template('avatar_edit.html', user=the_user, avatar_edit_form=avatar_edit_form,
                               avatar_upload_form=avatar_upload_form, title=u"Change avatar")
    else:
        abort(403)

app/main/user/templates/avatar_edit.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block styles %}
    {{ super() }}
    <link href="{{ url_for('static',filename='css/fileinput.min.css') }}" rel="stylesheet">
    <style>
        main {
            display: flex;
        }

        #input_area {

        }
    </style>
{% endblock %}
{% block mycontent %}
    <div class="jumbotron">
        <div class="row">
            {% if user.avatar_url() %}
                <div class="col-md-4">
                    <div class="media-object avatar avatar-large"
                         style="background-image: url({{ user.avatar_url() }})"></div>
                </div>
            {% endif %}
            <div class="col-md-6" id="input_area">
                <p>Please make sure you enter the correct one URL</p>
                <p>Uploaded image size cannot exceed 1Mb</p>
                <form method="post" class="form {% if avatar_edit_form.avatar_url.errors %} has-error{% endif -%}"
                      role="form" name="avatar_edit_form">
                    {{ avatar_edit_form.hidden_tag() }}
                    <div class="input-group  input-group">
                        {{ avatar_edit_form.avatar_url(placeholder="Input chain",class_="form-control") }}
                    <span class="input-group-btn">
                        {{ wtf.form_field(avatar_edit_form.submit,class_="btn btn-primary",button_map={'submit':'primary'}) }}
                    </span>
                    </div>
                    {% for error in avatar_edit_form.avatar_url.errors %}
                        <p class="help-block">{{ error }}</p>
                    {% endfor %}
                </form>
                <form method="post" class="form" enctype="multipart/form-data" role="form" name="avatar_edit_form">
                    {{ avatar_upload_form.hidden_tag() }}
                    {{ wtf.form_field(avatar_upload_form.avatar,class_="file",placehouder="upload image") }}
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{%- block scripts -%}
    {{ super() }}
    <script src="{{ url_for('static',filename='js/fileinput.min.js') }}"></script>
{%- endblock -%}

app/main/user/templates/user.html
{% extends "base.html" %}
{% from "bootstrap/pagination.html" import render_pagination %}
{% block mycontent %}
    <table class="table table-striped table-hover">
        <h1 class="page-header">{{ title }}</h1>
        <thead>
        <tr>
            <th>username</th>
            <th>User mailbox</th>
            <th>User borrowing book</th>
        </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr class="animated fadeIn delay-{{ loop.index0 }}">
                <td><a href="{{ url_for('user.detail',user_id=user.id) }}">{{ user.name }}</a></td>
                <td>{{ user.email }}</td>
                <td>{{ user.logs.count() }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% if pagination and pagination.pages > 1 %}
        <div class="container-fluid text-center">
            {{ render_pagination(pagination) }}
        </div>
    {% endif %}
{% endblock %}

app/main/user/templates/user_detail.html
{% extends "base.html" %}
{% from "bootstrap/pagination.html" import render_pagination %}
{% block mycontent %}
    <div class="jumbotron">
        <div class="row">
            {%- if user.avatar_url() -%}
                <div class="col-md-3 animated bounceIn">
                    {%- if current_user.id == user.id or current_user.can(Permission.UPDATE_OTHERS_INFORMATION) -%}
                        <a href="{{ url_for('user.avatar',user_id=user.id) }}" data-toggle="tooltip"
                           data-placement="bottom" title="点击修改头像">
                            <div class="avatar avatar-large"
                                 style="background-image: url({{ user.avatar_url() }})"></div>
                        </a>
                    {%- else -%}
                        <div class="avatar avatar-large"
                             style="background-image: url({{ user.avatar_url() }})"></div>
                    {%- endif -%}
                </div>
            {%- endif -%}
            <div class="col-md-6 col-md-offset-1 animated fadeIn">
                <h1 class="page-header">{{ user.name }}
                    {% if user.headline %}
                        <small>{{ user.headline }}</small>
                    {% endif %}

                </h1>

                <p>Email: {{ user.email }}</p>
                {% if user.major %}
                    <p>major: {{ user.major }}</p>
                {% endif %}
                  <p>Date of joining: {{ user.member_since.strftime('%d %B %Y - %H:%M:%S') }}</p>
                {% if current_user.id==user.id or current_user.can(Permission.UPDATE_OTHERS_INFORMATION) %}
                    <a class="btn btn-info" href="{{ url_for('user.edit',user_id=user.id) }}">edit information</a>
                {% endif %}
                {% if current_user.id==user.id %}
                    <a class="btn btn-danger" href="{{ url_for('auth.change_password',user_id=user.id) }}">change Password</a>
                {% endif %}

            </div>
        </div>


        {% if user.about_me_html %}
            <h2>
                <small>Personal profile</small>
            </h2>
            {{ user.about_me_html|safe }}
        {% elif user.about_me %}
            <p>{{ user.about_me }}</p>
        {% endif %}


    </div>

    <div class="well well-lg" id="log">
        <ul class="nav nav-tabs" role="tablist">
            {% if request.args.get('show',0)!='1' %}
                <li role="presentation" class="active"><a href="#log" role="tab">Current borrowing record</a></li>
                <li role="presentation"><a href="{{ url_for('user.detail',user_id=user.id,show=1,_anchor='log') }}"
                                           role="tab">Historical borrowing record</a>
                </li>
            {% else %}
                <li role="presentation"><a href="{{ url_for('user.detail',user_id=user.id,show=0,_anchor='log') }}"
                                           role="tab">Current borrowing record</a>
                </li>
                <li role="presentation" class="active"><a href="#log" role="tab">Historical borrowing record</a></li>
            {% endif %}
        </ul>
        <!-- Tab panes -->
        <div class="tab-content row">
            {% if request.args.get('show',0)!='1' %}
                <table class="table table-striped table-hover">
                    <thead>
                    <tr>
                        <th>Borrowing books</th>
                        <th class="hidden-xs">Borrow date</th>
                          <th class="hidden-xs">Date should be returned</th>
                        {%- if current_user.is_authenticated and current_user.id==user.id -%}
                            <th>operating</th>
                        {%- endif -%}
                    </tr>
                    </thead>
                    <tbody>
                    {% for log in logs %}
                        <tr class="animated fadeIn delay-{{ loop.index0 }}">
                            <td><a href="{{ url_for('book.detail',book_id=log.book.id) }}">{{ log.book.title }}</a>
                                <p class="visible-xs-block">Borrow date:<span
                                        class="line-wrap">{{ log.borrow_timestamp.strftime('%d %B %Y - %H:%M:%S') }}</span>
                                </p>
                                <p class="visible-xs-block">Date should be returned:<span
                                        class="line-wrap">{{ log.return_timestamp.strftime('%d %B %Y - %H:%M:%S') }}</span>
                                </p>
                            </td>
                            <td class="hidden-xs">{{ log.borrow_timestamp.strftime('%d %B %Y - %H:%M:%S') }}</td>
                            <td class="hidden-xs">{{ log.return_timestamp.strftime('%d %B %Y - %H:%M:%S') }}</td>
                            {%- if current_user.is_authenticated and current_user.id==user.id -%}
                                <td><a class="btn btn-primary"
                                       href="{{ url_for('log.book_return',log_id=log.id,next=request.path) }}">
                                       return</a></td>
                            {%- endif -%}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <table class="table table-striped table-hover">
                    <thead>
                    <tr>
                        <th>Historical borrowing</th>
                        <th class="hidden-xs">Borrow date</th>
                        <th class="hidden-xs">Date should be returned</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for log in logs %}
                        <tr class="animated fadeIn delay-{{ loop.index0 }}">
                            <td><a href="{{ url_for('book.detail',book_id=log.book.id) }}">{{ log.book.title }}</a>
                                <p class="visible-xs-block">
                                  Borrow date: <span
                                        class="line-wrap">{{ log.borrow_timestamp.strftime('%d %B %Y - %H:%M:%S') }}</span>
                                </p>
                                <p class="visible-xs-block">
                                  Return date: <span
                                        class="line-wrap">{{ log.return_timestamp.strftime('%d %B %Y - %H:%M:%S') }}</span>
                                </p>
                            </td>
                            <td class="hidden-xs">{{ log.borrow_timestamp.strftime('%d %B %Y - %H:%M:%S') }}</td>
                            <td class="hidden-xs">{{ log.return_timestamp.strftime('%d %B %Y - %H:%M:%S') }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                </div>
            {% endif %}
        {% if pagination and pagination.pages>1 %}
            <div class="container-fluid text-center">
                {{ render_pagination(pagination) }}
            </div>
        {% endif %}
    </div>
{% endblock %}
{% block scripts %}
    {{ super() }}
    <script>
        $('[data-toggle="tooltip"]').tooltip()
    </script>
{% endblock %}

app/main/user/templates/user_edit.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block mycontent %}
    <div class="jumbotron">
        <div class="row">
            {% if user.avatar_url() %}
                <div class="col-md-4 clearfix">
                    <div class="media-object avatar avatar-large"
                         style="background-image: url({{ user.avatar_url() }})"></div>
                </div>
            {% endif %}
            <div class="col-md-8">
                <h1 class="page-header">{{ user.name }}
                    <br>
                    <small>{{ user.email }}</small>
                </h1>
            </div>
        </div>
        <div class="row">
            <div class="well well-lg">
                <h3>{{ title }}</h3>
                {{ wtf.quick_form(form,button_map={'submit':'success'}) }}
            </div>
        </div>
    </div>
{% endblock %}

{%- block scripts -%}
    {{ super() }}
    {#    {{ pagedown.include_pagedown() }}#}
    <script src="{{ url_for('static',filename='js/Markdown.Converter.min.js') }}"></script>
    <script src="{{ url_for('static',filename='js/Markdown.Sanitizer.min.js') }}"></script>
{%- endblock -%}